# Generated by Django 4.1.7 on 2023-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_url', models.URLField(blank=True, null=True)),
                ('bsc_url', models.URLField(blank=True, null=True)),
                ('owner_eth_address', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_bsc_address', models.CharField(blank=True, max_length=255, null=True)),
                ('eth_third_party_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bsc_third_party_address', models.CharField(blank=True, max_length=255, null=True)),
                ('alice_eth_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bob_bsc_address', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_eth_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('deployed_bsc_contract_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_contract_compiled', models.BooleanField(default=False)),
                ('event_handler_status', models.BooleanField(default=False)),
                ('is_eth_deployed', models.BooleanField(default=False)),
                ('is_bsc_deployed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('T', 'Transfer'), ('A', 'Approval'), ('B', 'Burning'), ('M', 'Minting')], max_length=1)),
                ('payload', models.TextField()),
            ],
        ),
    ]
